[tool.pyright]
stubPath = "typings"
typeCheckingMode = "strict"
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUntypedFunctionDecorator = false
reportMissingTypeStubs = false
reportMissingModuleSource = false

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.poetry]
name = "pyalign"
version = "0.1.0"
description = ""
authors = ["winstxnhdw <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.385"
pytest = "^8.3.3"
numpy = "^2.1.2"
ruff = "^0.7.2"
