[tool.pylint.format]
good-names = ['x', 'y', 'z', 'id', 'ok']

[tool.pylint.messages_control]
disable = [
    'missing-module-docstring',
    'no-name-in-module',
    'useless-import-alias',
    'line-too-long',
    'too-many-arguments',
    'import-error',
    'used-before-assignment',
]

[tool.pyright]
stubPath = 'typings'
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUntypedFunctionDecorator = false
reportMissingTypeStubs = false
reportMissingModuleSource = false

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.poetry]
name = "pyalign"
version = "0.1.0"
description = ""
authors = ["winstxnhdw <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.358"
pylint = "^3.1.0"
pytest = "^8.1.1"
isort = "^5.13.2"
numpy = "^1.26.4"
