[tool.pyright]
stubPath = "typings"
typeCheckingMode = "strict"
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUntypedFunctionDecorator = false
reportMissingTypeStubs = false
reportMissingModuleSource = false

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D", "TCH004", "ANN001"]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.poetry]
name = "pyalign"
version = "0.1.0"
description = ""
authors = ["winstxnhdw <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.390"
pytest = "^8.3.4"
numpy = "2.2.0"
ruff = "^0.8.2"
nodejs-wheel-binaries = "^22.12.0"
