name: Dependabot

on: pull_request

jobs:
  build:
    uses: winstxnhdw/actions/.github/workflows/python.yml@main
    with:
      python-version: 3.11

  auto-merge:
    needs: build
    uses: winstxnhdw/actions/.github/workflows/dependabot-public.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
