name: Test

on:
  push:
    branches: main
    paths:
      - .github/workflows/main.yml
      - pyproject.toml
      - poetry.lock
      - '**.py'

jobs:
  test:
    uses: winstxnhdw/actions/.github/workflows/python.yml@main
