name: Test

on:
  workflow_call:
  push:
      branches: [main]
      paths:
          - '**.py'
          - .github/workflows/main.yml
          - pyproject.toml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry

      - name: Install Python dependencies
        run: poetry install

      - name: Lint
        run: poetry run pylint $(git ls-files '*.py')

      - name: Type Check
        run: poetry run pyright

      - name: Test
        run: poetry run pytest
